# Generated by Django 6.0 on 2026-01-25 13:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=15)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('lavadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='Servidor.lavadero')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_COLA', 'En Cola'), ('EN_PROCESO', 'En Proceso'), ('TERMINADO', 'Terminado'), ('ENTREGADO', 'Entregado')], default='EN_COLA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='Servidor.cliente')),
                ('lavadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='Servidor.lavadero')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'DaviPlata'), ('TARJETA', 'Tarjeta')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('lavadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='Servidor.lavadero')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='Servidor.orden')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador')], max_length=50)),
                ('lavadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='Servidor.lavadero')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto'), ('CAMIONETA_5', 'Camioneta (5 Pasajeros)'), ('CAMIONETA_7', 'Camioneta (7 Pasajeros)'), ('BICICLETA', 'Bicicleta')], default='CARRO', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('lavadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='Servidor.lavadero')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='servicios',
            field=models.ManyToManyField(related_name='ordenes', to='Servidor.servicio'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('CARRO', 'Automóvil'), ('MOTO', 'Motocicleta'), ('CAMIONETA_5', 'Camioneta (5 Pasajeros)'), ('CAMIONETA_7', 'Camioneta (7 Pasajeros)'), ('BICICLETA', 'Bicicleta')], max_length=20)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='Servidor.cliente')),
                ('lavadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='Servidor.lavadero')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='Servidor.vehiculo'),
        ),
    ]
