# Generated by Django 6.0 on 2026-01-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0002_alter_perfilusuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='tiempo_inicio_servicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
