# Generated by Django 6.0 on 2026-02-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0003_orden_tiempo_inicio_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='tiempo_inicio_servicio',
            field=models.TimeField(null=True),
        ),
    ]
