# Generated by Django 6.0 on 2026-02-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0004_alter_orden_tiempo_inicio_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='tiempo_adicional_servicio',
            field=models.CharField(choices=[('EN_COLA', 'En Cola'), ('EN_PROCESO', 'En Proceso'), ('TERMINADO', 'Terminado'), ('ENTREGADO', 'Entregado')], default='CERO', max_length=20),
        ),
    ]
