# Generated by Django 6.0 on 2026-01-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0004_lavadero_cliente_lavadero_orden_lavadero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto'), ('CAMIONETA_5', 'Camioneta (5 Pasajeros)'), ('CAMIONETA_7', 'Camioneta (7 Pasajeros)'), ('BICICLETA', 'Bicicleta')], default='CARRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('CARRO', 'Automóvil'), ('MOTO', 'Motocicleta'), ('CAMIONETA_5', 'Camioneta (5 Pasajeros)'), ('CAMIONETA_7', 'Camioneta (7 Pasajeros)'), ('BICICLETA', 'Bicicleta')], max_length=20),
        ),
    ]
