# Generated by Django 6.0 on 2026-01-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0005_alter_servicio_categoria_alter_vehiculo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='lavadero',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='lavadero',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='lavadero',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='lavadero',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='lavadero',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='lavadero',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Lavadero',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
