# Generated by Django 6.0 on 2026-02-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0006_alter_orden_tiempo_adicional_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='tiempo_adicional_servicio',
            field=models.CharField(blank=True, choices=[('CERO', '0 Minutos'), ('QUINCE', '15 Minutos'), ('TREINTA', '30 Minutos'), ('CUARENTA_Y_CINCO', '45 Minutos'), ('SESENTA', '1 Hora')], default='CERO', max_length=20, null=True),
        ),
    ]
