# Generated by Django 6.0 on 2026-01-19 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0006_remove_cliente_lavadero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='lavadero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='Servidor.lavadero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='lavadero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='Servidor.lavadero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='lavadero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='Servidor.lavadero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='Lavadero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='Servidor.lavadero'),
            preserve_default=False,
        ),
    ]
