# Generated by Django 6.0 on 2026-02-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0008_alter_orden_tiempo_adicional_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='tiempo_adicional_servicio',
            field=models.IntegerField(blank=True, choices=[(0, '0 Minutos'), (15, '15 Minutos'), (30, '30 Minutos'), (45, '45 Minutos'), (60, '1 Hora')], default=0, null=True),
        ),
    ]
