# Generated by Django 6.0 on 2026-02-06 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0009_alter_orden_tiempo_adicional_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operario_lavado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('lavadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operarios_lavado', to='Servidor.lavadero')),
            ],
        ),
    ]
