# Generated by Django 6.0 on 2026-02-06 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0011_servicio_operario_lavado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='operario_lavado',
        ),
        migrations.AddField(
            model_name='orden',
            name='Operario_lavado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='Servidor.operario_lavado'),
        ),
    ]
