# Generated by Django 6.0 on 2026-02-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0012_remove_servicio_operario_lavado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='Operario_lavado',
            new_name='operario_lavado',
        ),
    ]
