# Generated by Django 6.0 on 2026-02-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0013_rename_operario_lavado_orden_operario_lavado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operario_lavado',
            old_name='celular',
            new_name='celular_operario',
        ),
        migrations.RenameField(
            model_name='operario_lavado',
            old_name='correo',
            new_name='correo_operario',
        ),
        migrations.RenameField(
            model_name='operario_lavado',
            old_name='lavadero',
            new_name='lavadero_operario',
        ),
        migrations.RenameField(
            model_name='operario_lavado',
            old_name='nombre',
            new_name='nombre_operario',
        ),
    ]
