# Generated by Django 6.0 on 2026-03-24 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0014_rename_celular_operario_lavado_celular_operario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operario_lavado',
            name='celular_operario',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='operario_lavado',
            name='nombre_operario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_vehiculo', models.CharField(max_length=20)),
                ('tipo_vehiculo', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('lavadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='Servidor.lavadero')),
            ],
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='Servidor.categoria'),
        ),
    ]
