# Generated by Django 6.0 on 2026-03-24 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0015_alter_operario_lavado_celular_operario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo_vehiculo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='Servidor.categoria'),
        ),
    ]
