# Generated by Django 6.0 on 2026-03-29 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0016_alter_categoria_tipo_vehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha_gasto', models.DateTimeField(auto_now_add=True)),
                ('tipo_gasto', models.CharField(choices=[('ARRIENDO', 'Arriendo'), ('SERVICIOS_ENERGIA', 'Servicios Energia'), ('SERVICIOS_AGUA', 'Servicios Agua'), ('SERVICIOS_INTERNET', 'Servicios Internet'), ('SUMINISTROS_SHAMPOO', 'Suministros Shampoo'), ('SUMINISTROS_DESENGRASANTE', 'Suministros Desengrasante'), ('SUMINISTROS_PAÑOS', 'Suministros Paños'), ('SUMINISTROS_OTROS', 'Suministros Otros'), ('MANTENIMIENTO_HIDROLAVADORAS', 'Mantenimiento Hidrolavadoras'), ('MANTENIMIENTO_SHAMPUSERA', 'Mantenimiento Shampusera'), ('MANTENIMIENTO_COMPRESOR', 'Mantenimiento Compresor'), ('MANTENIMIENTO_OTROS', 'Mantenimiento Otros'), ('OTROS', 'Otros')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('lavadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='Servidor.lavadero')),
            ],
        ),
    ]
