# Generated by Django 6.0 on 2026-03-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0017_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha_gasto',
            field=models.DateTimeField(),
        ),
    ]
