# Generated by Django 6.0 on 2026-03-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0018_alter_gasto_fecha_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha_gasto',
            field=models.DateField(),
        ),
    ]
