# Generated by Django 6.0 on 2026-05-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0019_alter_gasto_fecha_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.CharField(choices=[('ARRIENDO', 'Arriendo'), ('SUELDOS', 'Sueldos'), ('SERVICIOS_ENERGIA', 'Servicios Energia'), ('SERVICIOS_AGUA', 'Servicios Agua'), ('SERVICIOS_INTERNET', 'Servicios Internet'), ('SUMINISTROS_SHAMPOO', 'Suministros Shampoo'), ('SUMINISTROS_DESENGRASANTE', 'Suministros Desengrasante'), ('SUMINISTROS_PAÑOS', 'Suministros Paños'), ('SUMINISTROS_OTROS', 'Suministros Otros'), ('MANTENIMIENTO_HIDROLAVADORAS', 'Mantenimiento Hidrolavadoras'), ('MANTENIMIENTO_SHAMPUSERA', 'Mantenimiento Shampusera'), ('MANTENIMIENTO_COMPRESOR', 'Mantenimiento Compresor'), ('MANTENIMIENTO_OTROS', 'Mantenimiento Otros'), ('OTROS', 'Otros')], max_length=50),
        ),
    ]
