# Generated by Django 6.0 on 2026-05-31 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0020_alter_gasto_tipo_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='operario_lavado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='Servidor.operario_lavado'),
        ),
    ]
