# Generated by Django 6.0 on 2026-05-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0021_gasto_operario_lavado'),
    ]

    operations = [
        migrations.AddField(
            model_name='operario_lavado',
            name='saldo_a_favor',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
