# Generated by Django 6.0 on 2026-05-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0022_operario_lavado_saldo_a_favor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='costo_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
