# Generated by Django 6.0 on 2026-06-01 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0023_orden_costo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='operario_lavado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='Servidor.operario_lavado'),
            preserve_default=False,
        ),
    ]
