# Generated by Django 6.0 on 2026-06-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0024_alter_gasto_operario_lavado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operario_lavado',
            name='nombre_operario',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
