# Generated by Django 6.0 on 2026-06-01 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servidor', '0025_alter_operario_lavado_nombre_operario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='operario_lavado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='Servidor.operario_lavado'),
        ),
    ]
